### PR TITLE
Add science category

### PR DESCRIPTION
**Pull request by yan12125**
Following up https://github.com/lxqt/lxqt-panel/pull/1868.

For example, with `lxqt-applications.menu` the main menu looks like:

圖片

I use breeze-icons. It will be great to see what it looks with other icon themes.

### CODE REVIEW

**Comment by stefonarch** [comment]
Looks good with Papirus too:

screen_area_mar_22:29:03_

In pcmanfm-qt (patched already here) one can see menu-chache at work: the new category appears after  1 or 2 seconds in `menu:///applications`

**Comment by stefonarch** [comment]
Plataro icons shows the same icon for both, gnome icons is missing "Education" icon. other sets I've not installed.

**Comment by stefonarch** [comment]
As we have now full control over categories: what about a "Science and Education" category? "Science, Math and Education" is probably to long in most languages.

**Comment by yan12125** [comment]
> As we have now full control over categories: what about a "Science and Education" category? "Science, Math and Education" is probably to long in most languages.

Brilliant! I implemented it in the latest commit.

**Comment by stefonarch** [comment]
It needs to be included in weblate then, by adding/modifying those files:
* menu/translations/education-science.directory.yaml 
` "Directory Name=Education & Science"`
* menu/desktop-directories/lxqt-education-science.directory.in:
```
 [Desktop Entry]
Icon=system-shutdown
Type=Directory

#TRANSLATIONS_DIR=../translations`
```

**Comment by yan12125** [comment]
Thanks for the hint. Building the new directory file seems working. Haven't tried to import it to weblate yet, though.

**Comment by stefonarch** [comment]
It works here fine too, GTM

**Comment by yan12125** [comment]
@stefonarch 
I moved the weblate component from Testing to LXQt Configuration (not sure if it's the best place) as https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-education-science-menu-directory/, and mirror translation settings from https://translate.lxqt-project.org/settings/lxqt-configuration/system-settings-category-name-in-menus/.

I've also added a webhook to https://github.com/lxqt/lxqt-menu-data/settings/hooks, using the same settings as https://github.com/lxqt/lxqt-config/settings/hooks.

Could you check if settings for the new translation component is good or not? If it looks good, we can unlock the component to accept translations.

**Comment by stefonarch** [comment]
It should be a component of `lxqt-settings`, not sure if can be moved there. Just for not doubling the repos.

>I've also added a webhook

Thanks!

Will update the draft blogpost and the README here later.

**Comment by yan12125** [comment]
> It should be a component of `lxqt-settings`, not sure if can be moved there. Just for not doubling the repos.

Do you mean [LXQt Configuration](https://translate.lxqt-project.org/projects/lxqt-configuration/)? It's already there. Also, I use a shared repo for the new component: `weblate://lxqt-configuration/lxqt-settings-category-name-in-menus`

**Comment by stefonarch** [comment]
Hm, I had a quick look but something has changed, don't understand it atm, I based three components on https://translate.lxqt-project.org/settings/lxqt-configuration/lxqt-settings-category-name-in-menus/#vcs and now some are based on the new one and this not.

**Comment by stefonarch** [comment]
I don't quite understand the new shared repo and how it's based on `lxqt-menu-data`, "lxqt-settings" is still the main repo? Anyway I unlocked it, it looks working.

I changed the name to  	`Education & Science (Category Name in menus) ` to be consistent.

**Comment by yan12125** [comment]
> I based three components on https://translate.lxqt-project.org/settings/lxqt-configuration/lxqt-settings-category-name-in-menus/#vcs

Looks like it's still the case for me. https://translate.lxqt-project.org/settings/lxqt-configuration/lxqt-settings-category-name-in-menus/#vcs points to https://github.com/lxqt/lxqt-menu-data/, and other components point to weblate://lxqt-configuration/lxqt-settings-category-name-in-menus.

**Comment by stefonarch** [comment]
` weblate://lxqt-configuration/lxqt-settings-category-name-in-menus.` this one  I don't understand where it is. When I try to add a new component based on an existing one it doesn't exist in the dropdown:
https://translate.lxqt-project.org/create/component/#existing

**Comment by yan12125** [comment]
Hmm, I can see `LXQt Configuration/LXQt  Settings (Category Name in menus)` from the dropdown menu there.

**Comment by stefonarch** [comment]
Yes, this is clear, but I can't see where this name is configured or comes from: ` weblate://lxqt-configuration/lxqt-settings-category-name-in-menus.`

**Pull request merged**
